### ISSUE TITLE
envFrom/ConfigMap not mapping environment variables to Docker container

### ISSUE THREAD

**Issue by tristanpemble** [datawire/telepresence#230]
I am using the `--docker-run` argument with `--swap-deployment` on Telepresence 0.60

My deployment's pod template uses `envFrom:`, which maps values from a ConfigMap into the environment.

The image running locally in Docker does not seem to receive the environment variables from this ConfigMap; it only receives the environment variables defined in the `env:` block of the template.

For example:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  EXAMPLE_ENVFROM: foobar
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: my-deployment
      labels:
        tier: whatever
    spec:
      containers:
        - name: alpine
          image: alpine
          command: ["/bin/sh", "-c", "env | grep EXAMPLE"]
          envFrom:
            - configMapRef:
                name: my-configmap
          env:
            - name: EXAMPLE_ENV
              value: foobar
```

```bash
λ kubectl apply -f ./test.yml
configmap "my-configmap" configured
deployment "my-deployment" configured
λ kubectl logs my-deployment-4135175423-3rzj5
EXAMPLE_ENVFROM=foobar
EXAMPLE_ENV=foobar
```

```bash
λ telepresence --swap-deployment my-deployment --docker-run alpine /bin/sh -c "env | grep EXAMPLE"
Volumes are rooted at $TELEPRESENCE_ROOT. See http://www.telepresence.io/howto/volumes.html for details.

EXAMPLE_ENV=foobar
```
