### ISSUE TITLE
Docker Compose support

### ISSUE THREAD

**Issue by itamarst** [datawire/telepresence#256]
Telepresence currently supports single containers. One potential user asked about Docker Compose support, which could be done.

Implementation notes:

By default Compose creates a new, shared network namespaces for each compose file (https://docs.docker.com/compose/networking/). It can however be overridden (https://docs.docker.com/compose/compose-file/#network_mode is one way, which matches the one Telepresence uses for `--docker-run`.) So we could either:

1. Run the compose file ourselves, telling it to use the proxy container's network namespace (and perhaps adding env variables and volumes).
2. Tell telepresence to use a particular network namespace, which could then be the one used by compse.

The latter option wouldn't provide env variables or volumes, but would be useful in general, since you could also attach to running Docker containers and start proxying their networking, rather than current UX which forces user to run container using `telepresence --docker-run`.

**Comment by prydonius** [comment]
Another possible option is to add the proxy container to the docker-compose file which would start up in the network created for that Compose project. Not 100% sure if that works in the same way as `--net=container:...`.

**Comment by prydonius** [comment]
For what it's worth, I was able to get this running by doing the following:

```
$ telepresence --new-deployment telepresence --method=container --docker-run -ti bitnami/minideb bash
```

I keep that container running to keep the telepresence deployment around the sshuttle? stuff around. Then, I copied the command from the telepresence proxy container that the above command starts and add a service to my docker-compose file:

```
version: '2'

services:
  telepresence:
    privileged: true
    image: datawire/telepresence-local:0.63
    command: ["proxy", "{\"port\": 59968, \"cidrs\": [\"10.0.0.0/24\"], \"expose_ports\": [], \"ip\": \"198.18.0.254\"}"]
    ports:
      - 8080:8080
  ui:
    tty: true # Enables debugging capabilities when attached to this container.
    image: bitnami/angular:2.0.0
    ports:
      - 4200:4200
    volumes:
      - ./src/ui:/app
    command: "ng serve --host 0.0.0.0"
  api:
    tty: true
    build: ./dev_env/api
    volumes:
      - ./src/api:/go/src/github.com/kubernetes-helm/monocular/src/api
      # Config example file
      - ./docs/config.example.yaml:/root/monocular/config/monocular.yaml
    environment:
      - ENVIRONMENT=development
    network_mode: service:telepresence
```

The API container then uses the telepresence network stack via network_mode. I could have used the container telepresence started with `network_mode: container:<id>`, but I saw this as an experiment to inject the telepresence container in the Compose file.

The downside was that I had to move the ports to the telepresence service instead of the API service.

It should be possible to have the telepresence CLI take a docker-compose file, inject the telepresence service and move all port mappings to that service and then start up. That way this could work with some Compose files out of the box. Does that sound about right?
