### ISSUE TITLE
Discover what cluster permissions Telepresence needs and why

### ISSUE THREAD

**Issue by ark3** [datawire/telepresence#569]
See #488 for a starting point on the current state of things. Once we have a handle on the what and the why, we can proceed with #568 to narrow and then document the set.

**Comment by ark3** [comment]
Plan:
1. Make a list of the kubectl commands that get run for typical invocations.
2. Run those commands manually with an underprivileged user, adding permissions based on the error messages we get.
3. Construct the final union of permissions as the answer for the way Tel works right now.

Consider addressing (the low hanging fruit of) #568 before step 2.

**Comment by ark3** [comment]
Step 1 may require some auditing, as in https://github.com/datawire/telepresence/issues/365#issuecomment-351486419, to do correctly.

**Comment by ark3** [comment]
For step 1, I traced everything that happens with swap-deployment and new-deployment using vpn-tcp and inject-tcp. It turns out that inject-tcp is a strict subset of vpn-tcp, since the latter adds a few commands to figure out IP address ranges.

swap-deployment:
```
kubectl version --short
kubectl --context ctx cluster-info
# swap vvv
kubectl --context ctx --namespace default get deployment -o json --export gather
kubectl --context ctx --namespace default delete deployment gather
kubectl --context ctx --namespace default apply -f -
# swap ^^^
kubectl --context ctx --namespace default get deployment -o json --export --selector=telepresence=blah
kubectl --context ctx --namespace default get pod -o json --export
kubectl --context ctx --namespace default get pod gather-123-abc -o json
kubectl --context ctx --namespace default logs -f gather-123-abc --container gather
kubectl --context ctx --namespace default port-forward gather-123-abc 61111:8022
kubectl --context ctx --namespace default exec gather-123-abc --container gather env
kubectl get nodes -o json
kubectl get services -o json
kubectl create service clusterip telepresence-1 --tcp=3000
kubectl get services -o json
kubectl delete service telepresence-1
# unswap vvv
kubectl --context ctx --namespace default delete deployment gather
kubectl --context ctx --namespace default apply -f -
# unswap ^^^
```

The commands without context/namespace are the #365 and #589 stuff.

new-deployment:
```
kubectl version --short
kubectl --context ctx cluster-info
# new vvv
kubectl --context ctx --namespace default delete --ignore-not-found all --selector=telepresence=blah
kubectl --context ctx --namespace default run --restart=Always --limits=cpu=100m,memory=256Mi --requests=cpu=25m,memory=64Mi gather --image=datawire/telepresence-k8s:0.82 --labels=telepresence=blah --port=5000 --expose
# new ^^^
kubectl --context ctx --namespace default get deployment -o json --export --selector=telepresence=blah
kubectl --context ctx --namespace default get pod -o json --export
kubectl --context ctx --namespace default get pod gather-123-abc -o json
kubectl --context ctx --namespace default logs -f gather-123-abc --container gather
kubectl --context ctx --namespace default port-forward gather-123-abc 61111:8022
kubectl --context ctx --namespace default exec gather-123-abc --container gather env
kubectl get nodes -o json
kubectl get services -o json
kubectl create service clusterip telepresence-1 --tcp=3000
kubectl get services -o json
kubectl delete service telepresence-1
# delete vvv
kubectl --context ctx --namespace default delete --ignore-not-found all --selector=telepresence=blah
# delete ^^^
```

The different between the two is that swap-deployment does get/delete/apply at the start, delete/apply at the end, whereas new-deployment does delete/run at the start and delete at the end.

**Comment by ark3** [comment]
The following works for everything except `k get nodes -o json`, which probably requires a `ClusterRole` or something (based on how Prometheus is usually set up). Failure to get nodes is non-fatal in Telepresence; it uses pod IP addresses as a fallback heuristic.

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tp-role
  namespace: tp
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["list", "create", "delete"]
- apiGroups: ["", "extensions"]
  resources: ["deployments"]
  verbs: ["list", "create", "get", "update", "delete"]
- apiGroups: ["", "extensions"]
  resources: ["deployments/scale"]
  verbs: ["get", "update"]
- apiGroups: ["", "extensions"]
  resources: ["replicasets"]
  verbs: ["list", "get", "update", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
```
